TITLE PROGRAMA SEGUNDO EXEMPLO PARA MANIPULAÇÃO DE VATORES USANDO BX
.MODEL SMALL
.DATA
    VETOR DB 0,0,0,0,0,0,0

.STACK 100H
.CODE
MAIN PROC
    MOV AX, @DATA
    MOV DS, AX                  ;IMPORTA O .DATA
    LEA DI, VETOR               ;COLOCA EM BX O OFFSET DE ENDEREÇO DO VETOR
    MOV CX, 7                   ;NÚMERO DE ELEMENTOS NO VETOR

    CALL LER

    CALL INVERTER

    LEA DI, VETOR           ;DI RECEBE O ENDEREÇO DO VETOR
    CALL IMPRIMIR
    
    MOV AH, 4CH
    INT 21H

MAIN ENDP

;LÊ CARACTERES PARA UM VETOR DE TAMANHO DEFINIDO PELO VALOR DE CX
;ALTERA O VALOR DE BX PARA O TAMANHO DO VETOR
;DI DEVE CONTER O ENDEREÇO DO VETOR
;RETORNA O VALOR DO ÚLTIMO CARACTERE DIGITADO EM AL, E 01H EM AH
LER PROC
    MOV BX, CX
    MOV AH, 1               ;RECEBE CARACTERE
    LEITURA:
        INT 21H

        MOV [DI], AL            ;COLOCA ESSE CARACTERE NO ENDEREÇO DI DA MEMÓRIA (VETOR)
        INC DI                  ;PRÓXIMA POSIÇÃO DO VETOR
        LOOP LEITURA
    XCHG DI, CX                 ;VOLTA O ÍNDICE DE DI PARA O INÍCIO DO VETOR E RETORNA O VALOR DO TAMANHO DO VETOR PARA CX
    RET
LER ENDP


;DI DEVE CONTER O ENDEREÇO DO VETOR
;CX DEVE CONTER O TAMANHO DO VETOR
;PERDE O CONTEÚDO QUE ESTAVA EM BX
INVERTER PROC
    MOV SI, DI                  ;SI PASSA A CONTER O ENDEREÇO DO INÍCIO DO VETOR
    DEC CX                      ;CX--, PARA REPRESENTAR O ÍNDICE DO ÚLTIMO ELEMENTO NO VETOR
    ADD DI, CX                  ;DI AGORA CONTÉM O ENDEREÇO DO ÚLTIMO ITEM DO VETOR
    INC CX                      ;CX VOLTA A CONTER O NÚMERO DE ELEMENTOS NO VETOR
    INVERTE:
        CMP DI, SI              ; COMPARA OS DOIS MARCADORES DE ÍNDICE
        JLE SAIR                ; SE OS ÍNDICES ESTIVEREM NO MESMO ELEMENTO (VETOR COM NÚMERO ÍMPAR DE ELEMENTOS) OU JÁ O TENHAM PASSADO DO MEIO (VETOR COM NÚMERO PAR DE ELEMENTOS), SAIR DO LOOP
        MOV BH, [SI]            ; BH RECEBE ELEMENTO DA PRIMEIRA METADE DO VETOR
        MOV BL, [DI]            ; BL RECEBE ELEMENTO DA SEGUNDA METADE DO VETOR
        
        MOV [DI], BH            ; ESCREVE O ELEMENTO DA PRIMEIRA METADE, NA SEGUNDA
        MOV [SI], BL            ; ESCREVE ELEMENTO DA SEGUNDA PARTE NA PRIMEIRA
        
        INC SI                  ; SI APONTA PARA O PRÓXIMO ELEMENTO
        DEC DI                  ; DI APONTA PARA O ELEMENTO ANTERIOR

        JMP INVERTE             ; VOLTA O LOOP.
    SAIR:
    RET
INVERTER ENDP


;DI DEVE CONTER O ENDEREÇO DO VETOR
;CX DEVE CONTER O TAMANHO DO VETOR
IMPRIMIR PROC
    MOV AH, 2               ;IMPRIMIR CARACTERE
    MOV DL, 10              ;PULA LINHA ANTES DE IMPRIMIR
    INT 21H
    PRINT:
        MOV DL, [DI]            ;COLOCA O VALOR NO ENDEREÇO DE MEMÓRIA BX, NO REGISTRADOR DL
        INC DI                  ;BX APONTA PARA O PRÓXIMO ELEMENTO
        INT 21H                 ;IMPRIME CARACTERE EM DL
        LOOP PRINT           ;REPETE LOOP

    RET
IMPRIMIR ENDP
END MAIN
