TITLE PROGRAMA SEGUNDO EXEMPLO PARA MANIPULAÇÃO DE VATORES USANDO SI OU DI
.MODEL SMALL
.DATA
    VETOR DB 1,1,1,2,2,2

.STACK 100H
.CODE
MAIN PROC
    MOV AX, @DATA
    MOV DS, AX              ;IMPORTA O .DATA
    MOV CX, 6               ;DEVE CONTER O NÚMERO DE ELEMENTOS NO VETOR

    CALL CONVERSOR

    MOV AH, 4CH             ;ENCERRA PROGRAMA
    INT 21H

MAIN ENDP

;SUB-ROTINA QUE RECEBE UM VETOR DE NÚMEROS DE 0 A 9 E OS CONVERTE PARA SEUS RESPECTIVOS CARACTERES E OS IMPRIME
;CX DEVE CONTER O NÚMERO DE ELEMENTOS DO VETOR
;DI SERÁ ZERADO E UTILIZADO COMO ÍNDICE DO VETOR
;DI RETORNARÁ COM O NÚMERO DE ELEMENTOS DENTRO DO VETOR
;O CONTEÚDO DE DL SERÁ ALTERADO PARA O VALOR DO ÚLTIMO ELEMENTO NO VETOR
CONVERSOR PROC
    XOR DL,DL               ;ZERA DL
    XOR DI, DI              ;ZERA DI --> ÍNDICE DO VETOR

    VOLTA:
        MOV DL, VETOR[DI]   ;ENVIA VALOR QUE ESTÁ ARMAZENADO NO VETOR, NO ÍNDICE DI, PARA DL
        INC DI              ;AVANÇA O ÍNDICE PARA O PRÓXIMO ITEM DO VETOR
        ADD DL, 30H         ;CONVERTE DE NÚMERO PARA CARACTERE
        MOV AH, 2           ;PODERIA ESTAR FORA DO LOOP, IMPRIME CARACTERE EM DL
        INT 21H             ;IMPRIME CARACTERE EM DL
    LOOP VOLTA

    RET
CONVERSOR ENDP
END MAIN