TITLE PROGRAMA SEGUNDO EXEMPLO PARA MANIPULAÇÃO DE VATORES USANDO BX
.MODEL SMALL
.DATA
    VETOR DB 1,1,1,2,2,2

.STACK 100H
.CODE
MAIN PROC
    MOV AX, @DATA
    MOV DS, AX              ;IMPORTA O .DATA
    MOV CX, 6               ;DEVE CONTER O NÚMERO DE ELEMENTOS NO VETOR

    CALL CONVERSOR

    MOV AH, 4CH             ;ENCERRA PROGRAMA
    INT 21H

MAIN ENDP

;SUB-ROTINA QUE RECEBE UM VETOR DE NÚMEROS DE 0 A 9 E OS CONVERTE PARA SEUS RESPECTIVOS CARACTERES E OS IMPRIME
;CX DEVE CONTER O NÚMERO DE ELEMENTOS DO VETOR
;BX SERÁ ZERADO E UTILIZADO COMO ÍNDICE DO VETOR
;O CONTEÚDO DE DL SERÁ ALTERADO PARA O VALOR DO ÚLTIMO ELEMENTO NO VETOR
CONVERSOR PROC
    XOR DL,DL               ;ZERA DL
    XOR BX, BX              ;ZERA BX

    VOLTA:
        MOV DL, VETOR[BX]   ;ENVIA VALOR QUE ESTÁ ARMAZENADO NO VETOR, NO ÍNDICE BX, PARA DL
        INC BX              ;AVANÇA O ÍNDICE PARA O PRÓXIMO ITEM DO VETOR
        ADD DL, 30H         ;CONVERTE DE NÚMERO PARA CARACTERE
        MOV AH, 2           ;PODERIA ESTAR FORA DO LOOP
        INT 21H             ;IMPRIME CARACTERE EM DL
    LOOP VOLTA    
    RET
CONVERSOR ENDP
END MAIN